resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 0
    instances:
      greetingRateLimiter:
        baseConfig: default
      calculateSumLimiter:
        baseConfig: default
